name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Install dependencies
        run: go get .

      - name: Build windows/amd64
        run: GOOS=windows GOARCH=amd64 go build -o ChunkCleaner-Win64.exe

      - name: Build linux/amd64
        run: GOOS=linux GOARCH=amd64 go build -o ChunkCleaner-Linux64 -v ./...

      - name: Debug - List files
        run: |
          ls ${{ github.workspace }}

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            ChunkCleaner-Win64.exe
            ChunkCleaner-Linux64
