name: Release

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - name: Run linter and tests
        run: go test -v -vet='all' ./...

      - name: Build windows/amd64
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') == true
        run: GOOS=windows GOARCH=amd64 go build -o ChunkCleaner-Win64.exe

      - name: Build linux/amd64
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') == true
        run: GOOS=linux GOARCH=amd64 go build -o ChunkCleaner-Linux64

      - name: Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') == true
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            ChunkCleaner-Win64.exe
            ChunkCleaner-Linux64
